name: OrbitalGraphs
version: "0.1.1"
license: "MPL-2.0"
date: 2021-09-02
description: |
    Computations with orbital graphs

authors:
    - name: Paula Hähndel
      url: https://algebra.mathematik.uni-halle.de/haehndel
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de
    - name: Wilf A. Wilson
      url: https://wilf.me

maintainers:
    - name: Paula Hähndel
      url: https://algebra.mathematik.uni-halle.de/haehndel
    - name: Wilf A. Wilson
      url: https://wilf.me

GAP: ">=4.8.2"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "Digraphs"
      version: ">= 0.12.1"
      url: "https://digraphs.github.io/Digraphs"

www: https://gap-packages.github.io/OrbitalGraphs
readme: README.md
packageinfo: https://gap-packages.github.io/OrbitalGraphs/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/OrbitalGraphs/releases/download/v0.1.1/OrbitalGraphs-0.1.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HPW21</span>]   <b class='BibAuthor'>Hähndel, P., Pfeiffer, M. and Wilson, W. A.</b>,
     <i class='BibTitle'>OrbitalGraphs, Computations with orbital graphs,
             Version 0.1.1</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/OrbitalGraphs">https://gap-packages.github.io/OrbitalGraphs</a></span>.
    </p>
    

bibtex: |
    @misc{ OrbitalGraphs0.1.1,
      author =           {H{\"a}hndel, P. and Pfeiffer, M. and Wilson, W. A.},
      title =            {{OrbitalGraphs},  Computations  with  orbital  graphs,
                          {V}ersion 0.1.1},
      month =            {Sep},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href   {https://gap-packages.github.io/OrbitalGraphs}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{OrbitalGraphs}}},
      printedkey =       {HPW21}
    }

